---
heat_template_version: pike

description: >
  Heat stack containing a Nova instance.

parameters:
  name:
    type: string
    label: Instance name
  flavor:
    type: string
    label: Flavor name or UUID
  image:
    type: string
    label: Image name or UUID
  volume_size:
    type: number
    label: Volume size in GB
  volume_type:
    type: string
    label: Volume type
  key_name:
    type: string
    label: SSH key pair name
  availability_zone:
    type: string
    label: Availability zone
    default: nova
  config_drive:
    type: boolean
    label: Whether to provide metadata via a configdrive
    default: false
  group_node_ports:
    type: json
    label: Nested list of port resources for all nodes in this group
  group_node_ips:
    type: json
    label: List of primary IPs for all nodes in this group
  node_idx:
    type: number
    label: Resource group index of this node

conditions:
  ports_gt_1: False
  ports_gt_2: False
#  ports_gt_1:
#    yaql:
#      data:
#        group_node_ports: { get_param: group_node_ports }
#      expression: $.data.group_node_ports[0].len() > 1
#  ports_gt_2:
#    yaql:
#      data:
#        group_node_ports: { get_param: group_node_ports }
#      expression: $.data.group_node_ports[0].len() > 2

resources:

  instance_volume:
    type: OS::Cinder::Volume
    properties:
      image: { get_param: image }
      size: { get_param: volume_size }
      volume_type: { get_param: volume_type }

  instance:
    type: OS::Nova::Server
    properties:
      name: { get_param: name }
      flavor: { get_param: flavor }
      block_device_mapping_v2:
        - delete_on_termination: False
          volume_id: { get_resource: instance_volume }
      key_name: { get_param: key_name }
      # FIXME: I would like to do this but Heat does not parse it:
      #networks: { get_param: [ group_node_ports, {get_param: node_idx} ] }
      #networks: 
      #  list_concat:
      #    - []
      #    - { get_param: [ group_node_ports, {get_param: node_idx} ] }
      #networks: 
      #  - { get_param: [ group_node_ports, {get_param: node_idx}, 0 ] }
      #networks:
      #  yaql:
      #    data:
      #      group_node_ports: { get_param: group_node_ports }
      #      node_idx: { get_param: node_idx }
      #    expression: $.data.group_node_ports[$.data.node_idx]
      #
      # FIXME: this works but is obviously limited to one port:
      #networks:
      #  - port: { get_param: [ group_node_ports, {get_param: node_idx}, 0, port ] }
      networks:
        list_concat:
          - [port: { get_param: [ group_node_ports, {get_param: node_idx}, 0, port ] }]
          - if:
            - ports_gt_1
            - [port: { get_param: [ group_node_ports, {get_param: node_idx}, 1, port ] }]
            - []
          - if:
            - ports_gt_2
            - [port: { get_param: [ group_node_ports, {get_param: node_idx}, 2, port ] }]
            - []
      availability_zone: { get_param: availability_zone }
      config_drive: { get_param: config_drive }

outputs:
  OS::stack_id:
    description: ID of the Nova instance
    value: { get_resource: instance }

  instance_data:
    description: ID of the primary IP
    value: 
      name: {get_param: name}
      ip: {get_param: [group_node_ips, {get_param: node_idx}]}
      id: {get_resource: instance} 
