---
heat_template_version: pike

description: >
  Heat stack template for a stack containing one Neutron port which is on
  a named network and subnet. A floating IP is created for the port.
  A second port is allocated on another network with SR-IOV port binding.

parameters:
  node_idx:
    type: number
    label: Node index within cluster group
  cluster_net:
    type: json
    label: Network names and subnets to which the nodes should be attached
  cluster_fips:
    type: json
    label: List of UUIDs of prealloacted floating IPs
    default: []
  router_networks:
    type: json
    label: Permit host to route IP traffic from specific networks through this port
    default: []

conditions:
  security_groups_set:
    yaql:
      expression: $.data.cluster_net.containsKey('security_groups')
      data:
        cluster_net: { get_param: [ cluster_net, 0 ] }

resources:

  port1:
    type: OS::Neutron::Port
    properties:
      network: { get_param: [ cluster_net, 0, net ] }
      security_groups:
        if:
          - security_groups_set
          - { get_param: [ cluster_net, 0, security_groups ] }
          - []
      fixed_ips:
        - subnet_id: { get_param: [ cluster_net, 0, subnet ] }

  # The SR-IOV port.
  # It might be presumptious to assume there are no security groups here.
  port2:
    type: OS::Neutron::Port
    properties:
      admin_state_up: True
      network: { get_param: [ cluster_net, 1, net ] }
      binding:vnic_type: direct
      security_groups: []
      fixed_ips:
        - subnet_id: { get_param: [ cluster_net, 1, subnet ] }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: [ cluster_net, 0, floating_net ] }

  floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: port1 }

outputs:
  OS::stack_id:
    description: The network list
    value: 
      - port1: { get_resource: port1 }
      - port2: { get_resource: port2 }

  networks:
    description: The network list
    value: 
      - port: { get_resource: port1 }
      - port: { get_resource: port2 }

  internal_ip:
    description: The IP assigned on the named cluster networks
    value:
      - - { get_attr: [ floating_ip, floating_ip_address ] }
        - { get_attr: [ port1, fixed_ips, 0, ip_address ] }
      - - { get_attr: [ port2, fixed_ips, 0, ip_address ] }

  primary_ip:
    description: The primary IP of the instance
    value: { get_attr: [ floating_ip, floating_ip_address ] }
